// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB86asmvobjedF4OC6Zv4TVxVY82KlRr5Y',
    appId: '1:284485582988:web:06e89d45ed6f827f2f3ba9',
    messagingSenderId: '284485582988',
    projectId: 'projectmaster-ab85d',
    authDomain: 'projectmaster-ab85d.firebaseapp.com',
    storageBucket: 'projectmaster-ab85d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUBff53CHQovEGT15TGAEKaH67AevUUYs',
    appId: '1:284485582988:android:74b0a21976defb592f3ba9',
    messagingSenderId: '284485582988',
    projectId: 'projectmaster-ab85d',
    storageBucket: 'projectmaster-ab85d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCcxJvEdssu9gksEs4dacA_b-xxCfZrio',
    appId: '1:284485582988:ios:3fa2366696b4fc9f2f3ba9',
    messagingSenderId: '284485582988',
    projectId: 'projectmaster-ab85d',
    storageBucket: 'projectmaster-ab85d.appspot.com',
    iosClientId: '284485582988-6i4ml17skq107r2njovamlgj2cmdrke4.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCcxJvEdssu9gksEs4dacA_b-xxCfZrio',
    appId: '1:284485582988:ios:3fa2366696b4fc9f2f3ba9',
    messagingSenderId: '284485582988',
    projectId: 'projectmaster-ab85d',
    storageBucket: 'projectmaster-ab85d.appspot.com',
    iosClientId: '284485582988-6i4ml17skq107r2njovamlgj2cmdrke4.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectMaster',
  );
}
